#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'git'
# cookbook 'gunicorn'
cookbook 'locale', :git => 'https://github.com/hw-cookbooks/locale.git'
cookbook 'postgresql', :git =>  'https://github.com/phlipper/chef-postgresql'
cookbook 'python', :git => 'https://github.com/poise/python'
cookbook 'sudo'
cookbook 'users'
